### ISSUE TITLE
Port the started Descent 2 campaign tracker

### ISSUE THREAD

**Issue by didymus13** [didymus13/portfolio#4]
Acceptance Requirements
* [ ] Create a new campaign
* [ ] Track progress of the campaign
* [ ] Record campaign state
* [ ] Track Character progress
* [ ] Track Overlord Progress
